name: Run Schedule RH


on:
  workflow_dispatch:
  # 每天 18:00（北京时间，等于UTC 10:00）
  schedule:
    - cron: '0 10 * * *'

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Set npm registry (加速)
        run: npm config set registry https://registry.npmmirror.com
      - name: Install dependencies (with cache)
        run: npm ci
      - name: Run script
        env:
          MY_USERNAME: ${{ secrets.MY_USERNAME }}
          MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
        run: node index.js
